global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'netflow-collector'
    static_configs:
      - targets: ['netflow-collector:8080']
    scrape_interval: 10s
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
